theme: jekyll-theme-midnight
title: Virtual Environment Studio Documentation
description: Sequential Workflow Guide for the VES Tools
# baseurl: "/studios-network.github.io" # the subpath of your site, e.g. /blog
url: "https://studios-network.github.io"
